<?php $this->layout('layout::default', [
    'title' => 'Mehmet Gökçe',
]) ?>


<div id="fh5co-about" class="animate-box">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>About Me</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <ul class="info">
                    <li><span class="first-block">Full Name:</span><span class="second-block">Mehmet Gökçe</span></li>
                    <li><span class="first-block">Email:</span><span class="second-block">mg@mehmetgoekce.com</span></li>
                    <li><span class="first-block">Website:</span><span class="second-block">www.mehmetgoekce.com</span></li>

                </ul>
            </div>
            <div class="col-md-8">
                <h2>Hello There!</h2>
                <h2>My Name is Mehmet </h2>
                <p>I'm from Augsburg, Germany</p>
                <p>I started programming in 1986. From the 8th grade I learned programming at school. In my studies of general computer science at the University of Applied Sciences Augsburg and the University of Applied Sciences Hannover, I have acquired the necessary theoretical knowledge. </p>
                <p>I'm a professional developer since 1998 and started my career in a large company in Germany. I've worked in many kind of projects and have had a broad range of experience with many technologies. I've a broad range of skills like Web Development, Application Programming, Network Administration, VOIP Programming and Data Engineering. <br>
                    Since 2018 I do Data Analytics for large companies. </p>
                <p>I'm founder and CEO of the company MEMOTEC.</p>
                <ul class="fh5co-social-icons">
                    <li><a href="https://twitter.com/mehmetgoekce"><i class="icon-twitter2"></i></a></li>
                    <li><a href="https://de.linkedin.com/in/mehmetgoekce"><i class="icon-linkedin2"></i></a></li>
                    <li><a href="https://github.com/MehmetGoekce"><i class="icon-github2"></i></a></li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-features" class="animate-box">
    <div class="container">
        <div class="services-padding">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                    <h2>My Services</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 text-center">
                    <div class="feature-left">
							<span class="icon">
								<i class="icon-cog"></i>
							</span>
                        <div class="feature-copy">
                            <h3>Web Development</h3>
                            <p>On the basis of leading open source components, I develop technically mature solutions that give you a lot of freedom in the design of your Internet presence.</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 text-center">
                    <div class="feature-left">
							<span class="icon">
								<i class="icon-paint-format"></i>
							</span>
                        <div class="feature-copy">
                            <h3>Responsive Webdesign</h3>
                            <p>Conception, design and implementation of a web presence for all devices and browsers. Attractive design, perfect function, optimal presentation.</p>
                        </div>
                    </div>

                </div>
                <div class="col-md-4 text-center">
                    <div class="feature-left">
							<span class="icon">
								<i class="icon-stats-dots"></i>
							</span>
                        <div class="feature-copy">
                            <h3>Data Analytics</h3>
                            <p>I cover the areas ETL, Reporting, OLAP / Analysis and Data Mining.</p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-4 text-center">

                    <div class="feature-left">
							<span class="icon">
								<i class="icon-bargraph"></i>
							</span>
                        <div class="feature-copy">
                            <h3>CRM</h3>
                            <p>Data integration for targeted customer segmentation and cross-channel reporting. Sales can be promoted through optimized sales flows and the management of contacts, orders and open shopping carts. Thanks to the Business Application Platform, the solution is flexible and innovative.
                            </p>
                        </div>
                    </div>

                </div>

                <div class="col-md-4 text-center">
                    <div class="feature-left">
							<span class="icon">
								<i class="icon-coin-euro"></i>
							</span>
                        <div class="feature-copy">
                            <h3>E-Commerce</h3>
                            <p>I care for your target groups and advise you on the design of the entire online value chain up to the delivery. From the shop to the fully integrated business solution.</p>
                        </div>
                    </div>

                </div>
                <div class="col-md-4 text-center">
                    <div class="feature-left">
							<span class="icon">
								<i class="icon-menu"></i>
							</span>
                        <div class="feature-copy">
                            <h3>PIM</h3>
                            <p>Manage and integrate every type and amount of digital data. With a PIM system, you can centrally and media-neutrally provide the data for multiple use across multiple IT systems, languages, output media and publications.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-blog">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Post on Medium</h2>
                <p>Writings</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="fh5co-blog animate-box">
                    <a href="https://medium.com/@mehmetgoekce/an-overview-of-business-problems-and-data-science-solutions-part-1-23e4bfeec7b3" class="blog-bg" style="background-image: url(images/numbers.jpeg);"></a>
                    <div class="blog-text">
                        <span class="posted_on">Oct 24,2018</span>
                        <h3><a href="https://medium.com/@mehmetgoekce/an-overview-of-business-problems-and-data-science-solutions-part-1-23e4bfeec7b3">An Overview of Business Problems and Data Science Solutions Part 1</a></h3>
                        <p>An important principle of data science is that data mining is a process. It includes the application of information technology, such as the automated discovery and evaluation of patterns from data. It also includes an analyst’s creativity, business knowledge, and common sense. Understanding the whole process helps to structure data mining projects.</p>
                        <ul class="stuff">
                            <li><a href="https://medium.com/@mehmetgoekce/an-overview-of-business-problems-and-data-science-solutions-part-1-23e4bfeec7b3">Read More<i class="icon-arrow-right22"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="fh5co-blog animate-box">
                    <a href="https://medium.com/@mehmetgoekce/an-overview-of-business-problems-and-data-science-solutions-part-2-940208d4ab4c" class="blog-bg" style="background-image: url(images/crisp.png);"></a>
                    <div class="blog-text">
                        <span class="posted_on">Oct 29, 2018</span>
                        <h3><a href="https://medium.com/@mehmetgoekce/an-overview-of-business-problems-and-data-science-solutions-part-2-940208d4ab4c">An Overview of Business Problems and Data Science Solutions — Part 2</a></h3>
                        <p>There is an important distinction related to data mining. First the difference between mining the data to find patterns and build models, and second using the results of data mining. Data Mining results inform the data mining process itself.</p>
                        <ul class="stuff">
                            <li><a href="https://medium.com/@mehmetgoekce/an-overview-of-business-problems-and-data-science-solutions-part-2-940208d4ab4c">Read More<i class="icon-arrow-right22"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

